spring:
  profiles:
    active: @spring.profiles.active@
  security:
    oauth2:
      client:
        registration:
          okta:
            client-id: 0oa4ue2d6F3r5SeVT5d6
            client-secret: wkVa6nTkmI52OWRcCNHjaRMxYRSF_EO-JJSVQY2b
            scope: openid, email, profile
        provider:
          okta:
            issuer-uri: https://dev-31089921.okta.com/oauth2/default